site_name: FZ - Parametric Scientific Computing Framework
site_description: Documentation for FZ and its plugins
site_author: Funz Team
site_url: https://funz.github.io
repo_url: https://github.com/Funz/fz
repo_name: Funz/fz

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - def_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Funz/fz
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/funz/
  version:
    provider: mike

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Core Concepts: getting-started/concepts.md
  - User Guide:
    - Core Functions:
      - fzi - Parse Input: user-guide/core-functions/fzi.md
      - fzc - Compile: user-guide/core-functions/fzc.md
      - fzo - Parse Output: user-guide/core-functions/fzo.md
      - fzr - Run Study: user-guide/core-functions/fzr.md
    - Model Definition: user-guide/model-definition.md
    - Calculators:
      - Overview: user-guide/calculators/overview.md
      - Local Shell: user-guide/calculators/shell.md
      - SSH Remote: user-guide/calculators/ssh.md
      - Cache: user-guide/calculators/cache.md
    - Advanced Features:
      - Parallel Execution: user-guide/advanced/parallel.md
      - Caching Strategy: user-guide/advanced/caching.md
      - Interrupt Handling: user-guide/advanced/interrupts.md
      - Formulas: user-guide/advanced/formulas.md
  - Plugins:
    - Overview: plugins/index.md
    - FZ-Moret: plugins/moret.md
    - FZ-MCNP: plugins/mcnp.md
    - FZ-Cathare: plugins/cathare.md
    - FZ-Cristal: plugins/cristal.md
    - FZ-Scale: plugins/scale.md
    - FZ-Telemac: plugins/telemac.md
  - Examples:
    - Perfect Gas Pressure: examples/perfectgas.md
    - Modelica/OpenModelica: examples/modelica.md
    - Remote HPC: examples/hpc.md
    - Google Colab Notebooks: examples/colab.md
  - Reference:
    - Configuration: reference/configuration.md
    - Environment Variables: reference/environment.md
    - Troubleshooting: reference/troubleshooting.md
    - API Reference: reference/api.md
  - Contributing:
    - Development: contributing/development.md
    - Testing: contributing/testing.md
